import { useState, useRef } from 'react'

interface Props {
  onReport: (markdown: string) => void
}

export function ReportInput({ onReport }: Props) {
  const [markdown, setMarkdown] = useState('')
  const [dragOver, setDragOver] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  function handleFile(file: File) {
    if (!file.name.endsWith('.md') && file.type !== 'text/markdown' && file.type !== 'text/plain') {
      return
    }
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target?.result as string
      if (text) {
        setMarkdown(text)
      }
    }
    reader.readAsText(file)
  }

  function handleDrop(e: React.DragEvent) {
    e.preventDefault()
    setDragOver(false)
    const file = e.dataTransfer.files[0]
    if (file) handleFile(file)
  }

  function handleDragOver(e: React.DragEvent) {
    e.preventDefault()
    setDragOver(true)
  }

  function handleDragLeave() {
    setDragOver(false)
  }

  function handleFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (file) handleFile(file)
  }

  function handleLoadExample() {
    setMarkdown(EXAMPLE_REPORT)
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Intro */}
      <div className="text-center space-y-2">
        <h2 className="text-xl font-semibold text-slate-900">View a QA Report</h2>
        <p className="text-sm text-slate-500 max-w-lg mx-auto">
          Paste a markdown QA report generated by the{' '}
          <code className="bg-slate-100 px-1.5 py-0.5 rounded text-indigo-600 font-mono text-xs">
            /qa-design-system
          </code>{' '}
          skill in Claude Code, or drop a <code className="bg-slate-100 px-1 py-0.5 rounded font-mono text-xs">.md</code> file.
        </p>
      </div>

      {/* Drop zone / textarea */}
      <div
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        className={`relative bg-white rounded-xl border-2 border-dashed transition-colors ${
          dragOver ? 'border-indigo-400 bg-indigo-50' : 'border-slate-200'
        }`}
      >
        <textarea
          value={markdown}
          onChange={(e) => setMarkdown(e.target.value)}
          placeholder="Paste your QA report markdown here, or drag and drop a .md file..."
          className="w-full h-64 px-4 py-3 text-sm font-mono text-slate-800 placeholder-slate-400 bg-transparent rounded-xl resize-y focus:outline-none focus:ring-2 focus:ring-indigo-500"
        />
        {dragOver && (
          <div className="absolute inset-0 flex items-center justify-center bg-indigo-50/80 rounded-xl pointer-events-none">
            <div className="text-indigo-600 font-medium text-sm">Drop .md file here</div>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex items-center justify-between">
        <div className="flex gap-2">
          <button
            onClick={() => fileInputRef.current?.click()}
            className="px-3 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
          >
            Upload .md file
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept=".md,.txt,.markdown"
            onChange={handleFileInput}
            className="hidden"
          />
          <button
            onClick={handleLoadExample}
            className="px-3 py-2 text-sm font-medium text-slate-400 hover:text-slate-600 transition-colors"
          >
            Load example
          </button>
        </div>
        <button
          onClick={() => onReport(markdown)}
          disabled={!markdown.trim()}
          className="px-6 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          View Report
        </button>
      </div>

      {/* How it works */}
      <div className="bg-white rounded-xl border border-slate-200 p-6">
        <h3 className="text-sm font-semibold text-slate-900 mb-3">How to generate a report</h3>
        <ol className="space-y-3 text-sm text-slate-600">
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-indigo-100 text-indigo-700 rounded-full flex items-center justify-center text-xs font-semibold">1</span>
            <span>
              Open <strong>Claude Code</strong> in your terminal
            </span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-indigo-100 text-indigo-700 rounded-full flex items-center justify-center text-xs font-semibold">2</span>
            <span>
              Run{' '}
              <code className="bg-slate-100 px-1.5 py-0.5 rounded text-indigo-600 font-mono text-xs">
                /qa-design-system
              </code>{' '}
              and provide your Figma + Storybook URLs
            </span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-indigo-100 text-indigo-700 rounded-full flex items-center justify-center text-xs font-semibold">3</span>
            <span>
              The skill uses Figma MCP + Playwright to extract specs and inspect the live component
            </span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 bg-indigo-100 text-indigo-700 rounded-full flex items-center justify-center text-xs font-semibold">4</span>
            <span>
              Copy the generated markdown report and paste it here to view it formatted
            </span>
          </li>
        </ol>
      </div>
    </div>
  )
}

const EXAMPLE_REPORT = `### Avatar — QA Report

**Date:** 2026-04-16
**Figma source:** https://www.figma.com/design/poaMyU7abAgL9VRhx4ygyy/Unity-DS-Components-Library?node-id=19-3853
**Storybook source:** https://unity-components.payfit.io/?path=/docs/component-reference-avatar--docs

#### Summary
- Total issues found: 5
- 🔴 Critical: 0 | 🟠 Major: 2 | 🟡 Minor: 2 | ⚪ Notes: 1

#### Issues

**🟠 Background color mismatch on hover state**
- **Variant/State:** Default / Hover
- **Property:** \`background-color\`
- **Figma value:** \`color/bg/hover\` → \`#E8E5EB\`
- **Storybook value:** \`#EDEDED\` (hardcoded)
- **Notes:** Storybook uses a hardcoded gray instead of the design token. This could diverge with future theme updates.

**🟠 Border radius inconsistency on size SM**
- **Variant/State:** Size SM
- **Property:** \`border-radius\`
- **Figma value:** \`radius/full\` → \`9999px\`
- **Storybook value:** \`8px\`
- **Notes:** SM variant renders with a rounded rect instead of a circle. All other sizes correctly use full rounding.

**🟡 Font weight difference in initials**
- **Variant/State:** All sizes / Default (with initials)
- **Property:** \`font-weight\`
- **Figma value:** \`600\` (Semi Bold)
- **Storybook value:** \`500\` (Medium)
- **Notes:** Subtle difference, only noticeable at larger sizes.

**🟡 Shadow opacity mismatch**
- **Variant/State:** Size LG / Default
- **Property:** \`box-shadow\`
- **Figma value:** \`shadow/sm\` → \`rgba(0,0,0,0.08) 0 1px 2px\`
- **Storybook value:** \`rgba(0,0,0,0.12) 0 1px 2px\`
- **Notes:** Shadow is slightly more pronounced in Storybook.

**⚪ Avatar xs (16px) size not compared**
- **Notes:** Per QA rules, the Avatar xs (16px) size is a known exception and was excluded from comparison.

#### Accessibility check
- ✅ Color contrast: all text-on-background combinations meet WCAG AA (4.5:1+)
- ✅ Focus ring: visible 2px indigo outline on Tab focus
- ⚠️ Missing \`aria-label\` on avatar when only image is shown (no initials fallback text)

#### Token consistency matrix

| Property | Default | Hover | Focus | Active | Disabled |
|----------|---------|-------|-------|--------|----------|
| background (Figma) | \`color/bg/default\` | \`color/bg/hover\` | \`color/bg/focus\` | \`color/bg/active\` | \`color/bg/disabled\` |
| background (Storybook) | \`color/bg/default\` | ⚠️ \`#EDEDED\` | \`color/bg/focus\` | \`color/bg/active\` | \`color/bg/disabled\` |
| border (Figma) | none | none | \`color/border/focus\` | none | none |
| border (Storybook) | none | none | \`color/border/focus\` | none | none |

#### Checklist of compared properties

| Property | XS | SM | MD | LG | XL |
|----------|----|----|----|----|-----|
| width/height | — | ✅ | ✅ | ✅ | ✅ |
| border-radius | — | ⚠️ | ✅ | ✅ | ✅ |
| background | — | ✅ | ✅ | ✅ | ✅ |
| font-size | — | ✅ | ✅ | ✅ | ✅ |
| font-weight | — | ⚠️ | ⚠️ | ⚠️ | ⚠️ |
| box-shadow | — | ✅ | ✅ | ⚠️ | ✅ |
| opacity | — | ✅ | ✅ | ✅ | ✅ |
`
